app:
  name: judicial-backend

services:
  - name: api
    type: web
    runtime: node
    resources:
      instance_type: free
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8000"
    build:
      build_command: npm install
      run_command: npm start
    ports:
      - port: 8000
        protocol: http
    health_checks:
      - port: 8000
        path: /health
        interval: 30
